'use client';
import { FormEvent, useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/browser';

type Project={id:string;name:string;description:string|null};
type Result={totals:{generation:number;demand:number;directGenerationToLoad:number;batteryChargeInput:number;batteryDischargeDelivered:number;curtailed:number;unmet:number;finalSocKwh:number};steps:Array<{generation:number;demand:number;socKwh:number;unmet:number}>};

export default function Dashboard(){
 const [projects,setProjects]=useState<Project[]>([]); const [projectId,setProjectId]=useState(''); const [name,setName]=useState(''); const [error,setError]=useState(''); const [result,setResult]=useState<Result|null>(null); const [busy,setBusy]=useState(false);
 const [generation,setGeneration]=useState('5,5,2,8'); const [demand,setDemand]=useState('4,6,5,4'); const [capacity,setCapacity]=useState('5'); const [soc,setSoc]=useState('2');
 async function load(){const r=await fetch('/api/projects'); if(r.ok){const d=await r.json();setProjects(d);if(d[0])setProjectId(d[0].id)}else setError('Unable to load projects');}
 useEffect(()=>{load()},[]);
 async function createProject(e:FormEvent){e.preventDefault();setError('');const r=await fetch('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});const d=await r.json();if(!r.ok){setError(d.error||'Failed');return}setProjects(p=>[d,...p]);setProjectId(d.id);setName('');}
 async function simulate(e:FormEvent){e.preventDefault();setBusy(true);setError('');setResult(null);try{if(!projectId)throw new Error('Create or select a project first');const gp=generation.split(',').map(Number),dp=demand.split(',').map(Number);if(gp.some(n=>!Number.isFinite(n))||dp.some(n=>!Number.isFinite(n)))throw new Error('Profiles must contain numbers');const sr=await fetch('/api/scenarios',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,name:'Quick Scenario',generationProfile:gp,demandProfile:dp,batteryCapacityKwh:Number(capacity),initialSocKwh:Number(soc),chargeEfficiency:.9,dischargeEfficiency:.9})});const sc=await sr.json();if(!sr.ok)throw new Error(sc.error);const rr=await fetch('/api/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenarioId:sc.id,input:{generationProfile:gp,demandProfile:dp,batteryCapacityKwh:Number(capacity),initialSocKwh:Number(soc),chargeEfficiency:.9,dischargeEfficiency:.9}})});const out=await rr.json();if(!rr.ok)throw new Error(out.error);setResult(out.result);}catch(e){setError(e instanceof Error?e.message:'Simulation failed')}finally{setBusy(false)}}
 async function signOut(){await createClient().auth.signOut();location.href='/login'}
 return <><nav><strong>IntelligentEnergy</strong><button onClick={signOut}>Sign out</button></nav><main className="container"><h1>Energy Dashboard</h1><div className="grid grid-3"><section className="card"><h2>Projects</h2><form onSubmit={createProject}><input placeholder="New project name" value={name} onChange={e=>setName(e.target.value)} required/><button>Create project</button></form><select style={{width:'100%',marginTop:14,padding:10}} value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></section><section className="card" style={{gridColumn:'span 2'}}><h2>Run simulation</h2><form onSubmit={simulate}><label>Generation profile (kWh/step)<input value={generation} onChange={e=>setGeneration(e.target.value)}/></label><label>Demand profile (kWh/step)<input value={demand} onChange={e=>setDemand(e.target.value)}/></label><label>Battery capacity (kWh)<input type="number" min="0" step="any" value={capacity} onChange={e=>setCapacity(e.target.value)}/></label><label>Initial SOC (kWh)<input type="number" min="0" step="any" value={soc} onChange={e=>setSoc(e.target.value)}/></label><button disabled={busy}>{busy?'Running…':'Run Phase 1 simulation'}</button></form></section></div>{error&&<p className="error">{error}</p>}{result&&<section className="card" style={{marginTop:20}}><h2>Simulation results</h2><div className="grid grid-3">{Object.entries(result.totals).map(([k,v])=><div key={k}><strong>{k}</strong><div>{Number(v).toFixed(3)} kWh</div></div>)}</div><h3>Time steps</h3><div style={{overflowX:'auto'}}><table><thead><tr><th>Step</th><th>Generation</th><th>Demand</th><th>SOC</th><th>Unmet</th></tr></thead><tbody>{result.steps.map((s,i)=><tr key={i}><td>{i+1}</td><td>{s.generation}</td><td>{s.demand}</td><td>{s.socKwh.toFixed(3)}</td><td>{s.unmet.toFixed(3)}</td></tr>)}</tbody></table></div></section>}</main></>;
}
